export enum textTypes {
  TITLE_BOLD = 'TITLE_BOLD', //  24px
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_LIGHT = 'TITLE_LIGHT',
  SUBTITLE_BOLD = 'SUBTITLE_BOLD', //  20px
  SUBTITLE_REGULAR = 'SUBTITLE_REGULAR',
  SUBTITLE_LIGHT = 'SUBTITLE_LIGHT',
  PARAGRAPH_BOLD = 'PARAGRAPH_BOLD', //  14px
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
  PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
  SMALLPARAGRAPH_BOLD = 'SMALLPARAGRAPH_BOLD', //  10px
  SMALLPARAGRAPH_REGULAR = 'SMALLPARAGRAPH_REGULAR',
  SMALLPARAGRAPH_LIGHT = 'SMALLPARAGRAPH_LIGHT',
  BUTTON_BOLD = 'BUTTON_BOLD', //  10px
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_LIGHT = 'BUTTON_LIGHT',
}
